### ISSUE TITLE
"incomplete" files passed to melody.evaluate should pass a warning.

### ISSUE THREAD

**Issue by rabitt** [craffel/mir_eval#103]
f0 annotations are often output by algorithms with the "unvoiced" frames omitted, resulting in an incomplete set of time stamps. I was evaluating one of these types of melody output against a ground truth (with all time stamps, f0=0 for unvoiced frames), and melody.evaluate runs without problems.

After a brief talk with @justinsalamon, I learned that melody.evaluate is actually interpolating the missing f0 values. I can see use cases where you would want this behavior, but I might not have caught this problem. So, maybe melody.evaluate should pass a warning if a file with unevenly spaced time stamps is inputted, or, better yet, have a parameter to "fill missing frames".

Example files can be found [here](https://gist.github.com/rabitt/c45b969adf927cbe14b2)

**Comment by craffel** [comment]
@rabitt @justinsalamon any progress/plan on adding this functionality?

**Comment by justinsalamon** [comment]
I'll work on this later on this week. I agree with @craffel's last suggestion - by default we should only issue a warning when the time series is non-uniform, and provide the option to explicitly active an intermediate "silence imputation" step.

**Comment by craffel** [comment]
@justinsalamon Do you think you'll work on this today or tomorrow?  Trying to get a release out by tomorrow night.  If not, I can look into it.

**Comment by justinsalamon** [comment]
@craffel I'm in the middle of a shitstorm of work, topped by the icing of having to move apartments. Right now the only "builds" I'm working on is disassembling my ikea furniture :hammer:  Wasn't aware there was a release pending, sorry. In this case, you might want to take a quick look.

**Comment by craffel** [comment]
How would you (and @rabitt) feel for now just issuing a warning when `not np.allclose(np.diff(times), np.diff(times).mean())`?  And then we can add the functionality for files with gaps at a later date, if @rabitt wants to port her code?

**Comment by justinsalamon** [comment]
I think that could work for now, yes. Something along the lines of "Warning: non-uniform timestamps detected. Pitch will be linearly interpolated between every pair of points. Silences should be indicated by nonpositive values (as per MIREX)." (just a suggestion).

**Comment by craffel** [comment]
PR: #142
