### ISSUE TITLE
Use Travis CI

### ISSUE THREAD

**Issue by nils-werner** [craffel/mir_eval#107]
Since you already have tests it is generally a good idea to have [Travis CI](https://travis-ci.org/craffel/mir_eval) to actually run them for every commit and pull request.

A simple `.travis.yml` could look like (not tested)

    language: python
    python:
        - "2.7"
        - "3.3"
        - "3.4"
    virtualenv:
        system_site_packages: true
    install:
        - sudo apt-get update -qq
        - if [[ $TRAVIS_PYTHON_VERSION == *"2."* ]]; then sudo apt-get install python-numpy python-scipy; fi
        - if [[ $TRAVIS_PYTHON_VERSION == *"3."* ]]; then sudo apt-get install python3-numpy python3-scipy; fi
        - pip install -e .
        - pip install nosetests sphinx
    script:
        - nosetests
        - python setup.py build_sphinx
        - python setup.py egg_info -b.dev sdist --formats gztar

**Comment by craffel** [comment]
Yes, this is something we've been meaning to add!  Thanks for this.  We currently aren't officially supporting Python 3 (#74).  Otherwise, do you want to create a PR for this?

**Comment by nils-werner** [comment]
I'd love to. I suggest you added this repo to Travis first, so my PR will immediately be tested.

**Comment by craffel** [comment]
OK, I added this repo to travis.

**Comment by nils-werner** [comment]
I've implemented it all in PR #113. Sorry for the other messy PRs before :-)
