### ISSUE TITLE
Docstrings in pattern functions need more detail

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#120]
The documentation for `patterns.evaluate` and `io.load_patterns` does not actually explain the data structure produced by the loader, or required by the evaluator.

In `load_patterns`, you get
```
Returns
-------
pattern_list : list
    The list of patterns, containing all their occurrences,
    using the following format::

        pattern_list = [pattern1, ..., patternN]
        pattern = [occurrence1, ..., occurrenceM]
        occurrence = [onset_midi1, ..., onset_midiO]
        onset_midi = (onset_time, midi_number)

    E.g.::
        P = [[[(77.0, 67.0), (77.5, 77.0), ... ]]]
```
but this does not explain what `N`, `M`, and `O` are.

**Comment by craffel** [comment]
What do you want it to say, "where `N` is the number of patterns, `M` is the number of occurrences, and `O` is the number of onsets"?  Or just remove the indexes, e.g. `pattern_list = [patterns ...]`?  Is the description "Loads the patters contained in the filename and puts them into a list of patterns, each pattern being a list of occurrence, and each occurrence being a list of (onset, midi) pairs." not enough?  @urinieto would need to confirm the actual semantics here, I am just guessing how the pattern stuff works.

**Comment by bmcfee** [comment]
> What do you want it to say, "where N is the number of patterns, M is the number of occurrences, and O is the number of onsets"?

Better yet:
```
where N is the number of patterns, M[i] is the number of occurrences of the i'th pattern, and O[j] is the number of onsets in the j'th occurrence
```
As it currently reads, it's not clear that there is a separate M for each pattern, and a separate O for each occurrence.

> Is the description "Loads the patters contained in the filename and puts them into a list of patterns, each pattern being a list of occurrence, and each occurrence being a list of (onset, midi) pairs." not enough?

A small, but complete example would help a lot here.

**Comment by urinieto** [comment]
> Better yet:
> ```
> where N is the number of patterns, M[i] is the number of occurrences of the i'th pattern, and O[j] is the number of onsets in the j'th occurrence
>```

That's exactly it. I can come up with a little example and update it myself if you want.

**Comment by craffel** [comment]
Ok, feel free to make these changes, or get @urinieto to do it.  If neither of you do it, I can try to hack at it eventually, but I have virtually no experience/understanding of the pattern discovery task.

**Comment by urinieto** [comment]
> I have virtually no experience/understanding of the pattern discovery task.

Lucky you.

**Comment by urinieto** [comment]
Done it. I added the 5th symphony canonical motive as an example. Let me know if you need anything else.

**Comment by urinieto** [comment]
Should we close this?

**Comment by bmcfee** [comment]
Looks good!
