### ISSUE TITLE
beat.information_gain fails when <2 beats

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#121]
This comes through from `beat._get_entropy`, where it looks at the inter-onset interval without checking that the beat array is large enough.

There should probably be:

* an exception in entropy if there are fewer than two beats
* a try-except in information_gain which sets the score to 0 (or nan, but i think 0 is appropriate here).  This way, a call to `beat.evaluate()` will still work, even when one of the metrics fails.  Single-beat annotations are legal for something like f-measure, so kicking the exception all the way upstream doesn't entirely make sense.

**Comment by craffel** [comment]
Hm, I guess this should have been covered when we were thinking about #44.  I'm surprised that other metrics don't also fail when there's only when annotation - is information gain the only one you checked?  I'd like to avoid an exception or NaN; see discussion starting here https://github.com/craffel/mir_eval/issues/43#issuecomment-40770763.  I need to investigate, but I think we actually just need some special logic - the beat error histogram, when there is only one estimated beat, should just have a single non-zero bin at the error corresponding to the difference between the one estimated beat and the closest reference beat; when there is only one reference beat, we should compare all estimated beats to the single reference beat, right?

**Comment by bmcfee** [comment]
> I'm surprised that other metrics don't also fail when there's only when annotation - is information gain the only one you checked?

No, but I haven't done a thorough test either.  This one just happened to come up in some corner cases of a parameter optimization I'm running.



> I need to investigate, but I think we actually just need some special logic

Sure.  I was thinking the exception would be caught within mir_eval and handled as a special case, not punted up to the user.  You can hard-wire the special case without exceptions also, depending on which ends up being cleaner.

**Comment by craffel** [comment]
Moving this issue to a bigger issue #122
