### ISSUE TITLE
Don't require that tempi be provided in ascending order

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#124]
Currently, the docstring for `tempo.detection` states that `reference_tempi` and `estimated_tempi` be provided as two-element `np.ndarray`s, such that their first entry is smaller than their second.  Why not just require that two tempi are passed for both, and simply sort them?  I believe it's just a matter of comparing them in the correct order, unless I'm mistaken.

**Comment by bmcfee** [comment]
Sure, we can do that.  It's mainly there to follow the mirex convention.  More generally, `weight` is the relative weight of the first tempo vs the second, and the actual ordering doesn't matter at all.  By convention, it applies to the slower of the two, but that's not necessary for the metric to work.

Maybe we should just clarify the docstring instead?

**Comment by craffel** [comment]
Either is fine.

**Comment by craffel** [comment]
Fixed in #131
