### ISSUE TITLE
Travis fails, rake not found

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#126]
Travis is currently reporting:

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

**Comment by bmcfee** [comment]
Looks like this is because .travis.yml is only in develop, not master.

**Comment by craffel** [comment]
Indeed.  We should just merge develop into master and handle things in the normal way.

**Comment by clucasalcantara** [comment]
`gem install rake` On my server solved the problem. You could also include this into a `pre-install.sh` script

**Comment by AquiGorka** [comment]
I had the same issue, in my case I had not setup a build script and apparently by default travis tries to test common configurations to the language of choice > ruby via rake: no rake = no test, then build failed.

**Comment by parvezk** [comment]
It could be an issue with travis file name. Please ensure its .travis.yml

**Comment by cesar-valdez** [comment]
hello, can be tabs in the file with extension yml
