### ISSUE TITLE
travis build on 3.4, 3.5?

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#129]
The current config is set for 2.7 and 3.3; we should at least bump to 3.4 since [nobody really uses 3.3](http://www.randalolson.com/2015/01/30/python-usage-survey-2014/).  3.5 would be nice as well.

**Comment by craffel** [comment]
Sounds good, go for it!

**Comment by bmcfee** [comment]
Any objection to adding coveralls support, while i'm at it?

**Comment by craffel** [comment]
No, please do!  It was on some to-do list somewhere.

**Comment by bmcfee** [comment]
Roger.

Also, any thoughts about replacing this wheels download with a miniconda environment?  Conda's scipy packages get updated much more regularly, apparently.

**Comment by craffel** [comment]
> Also, any thoughts about replacing this wheels download with a miniconda environment? Conda's scipy packages get updated much more regularly, apparently.

Yeah, I'd prefer miniconda.  I actually thought that's what we were using, but I didn't add the travis support, so what do I know.

**Comment by bmcfee** [comment]
Alright.  Maybe i'll rename this issue to "generally fix up the CI configs"

**Comment by craffel** [comment]
:+1:

**Comment by bmcfee** [comment]
Got it.  Miniconda doesn't yet have 3.5 support http://continuum.io/blog/python35 , so let's hold off on that one for now.

**Comment by craffel** [comment]
Closed via #130.
