### ISSUE TITLE
event_validation limits onset times to <=30000

### ISSUE THREAD

**Issue by justinsalamon** [craffel/mir_eval#132]
It looks like the maximum allowable onset time is [hardcoded](https://github.com/craffel/mir_eval/blob/master/mir_eval/onset.py#L32) to 30000. We're using mir_eval for some environmental recordings that are longer than 8 hours, and so the code spits a value error and dies.
```
File "/usr/local/lib/python2.7/site-packages/mir_eval/onset.py", line 99, in f_measure
    validate(reference_onsets, estimated_onsets)
  File "/usr/local/lib/python2.7/site-packages/mir_eval/onset.py", line 56, in validate
    util.validate_events(onsets, MAX_TIME)
  File "/usr/local/lib/python2.7/site-packages/mir_eval/util.py", line 634, in validate_events
    'seconds?)'.format(events.max(), max_time))
ValueError: An event at time 35336.67 was found which is greater than the maximum allowable time of max_time = 30000.0 (did you supply event times in seconds?)
```
Shouldn't this threshold be an optional input parameter?

**Comment by craffel** [comment]
It's not hardcoded, just set `mir_eval.onset.MAX_TIME = 1e100`before calling any functions in `mir_eval.onset`.  This was discussed briefly here https://github.com/craffel/mir_eval/issues/87

**Comment by justinsalamon** [comment]
righty! cheers
