### ISSUE TITLE
filter_kwargs and python 3.5 compatibility

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#133]
`util.filter_kwargs` uses the inspect module's `getargspec` function [here](https://github.com/craffel/mir_eval/blob/master/mir_eval/util.py#L715), which is deprecated in python 3.5.

In python 3, this has been replaced with the `signature` function (see [here](https://docs.python.org/3/library/inspect.html#inspect.signature)), which sadly doesn't work on py2.

You might be able to side-step this by using `six.get_function_defaults()`.

Alternatievly, our buddies at sklearn have a fix for this [here](https://github.com/scikit-learn/scikit-learn/commit/6966881328c256bbef37752cce23bbac8e23fb27).

**Comment by craffel** [comment]
> You might be able to side-step this by using six.get_function_defaults().

I don't think so, it looks like that function just retrieves default values for arguments, rather than the name of each argument (what we need).

So, as far as you know, none of the python 2 backport libraries include code for this?  It looks like sklearn has just copied this https://pypi.python.org/pypi/funcsigs into their library.  I'd be ok with adding funcsigs as a dependency, as it's pure Python.

**Comment by bmcfee** [comment]
> it looks like that function just retrieves default values for arguments,

Yeah, you're right.  I realized that after suggesting it, but forgot to edit the comment.  Meanwhile: paging @amueller for any additional insight on this.

**Comment by craffel** [comment]
Here's a little function which re-implements the part of `getargspec` we need:
```Python
def get_arg_names(function):
    func_code = function.func_code
    return func_code.co_varnames[:func_code.co_argcount]
```
Usage:
```Python
>>> def foo(a, b, c=100):
...    d = 30
...    return a + b, c + d
...
>>> print get_arg_names(foo)
('a', 'b', 'c')
```
Spot anything wrong with that?  If not, I'll submit a PR to change the call to `getargspec` to the `func_code` method above.

**Comment by bmcfee** [comment]
Seems legit, I guess?  We'll probably need to set up a test environment for py3.5, but afaik travis/miniconda don't have this yet.  (There is a full anaconda distribution with 3.5, but that's a big heavy for test environments.)

**Comment by amueller** [comment]
https://travis-ci.org/scikit-learn/scikit-learn/jobs/85767336#L1012

**Comment by bmcfee** [comment]
Huh.  Well shut my mouth!  Last I checked, miniconda didn't have 3.5.

**Comment by craffel** [comment]
Ok.  I will try to do this all in one go then.
