### ISSUE TITLE
util.boundaries_to_intervals with labels is weird

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#151]
When `labels=None` (the default), `None` is returned.  We don't have any tests or code anywhere that doesn't use `labels=None`.  When `labels != None`, `labels[-1]` is returned.  There's no test that `len(labels) == len(boundaries)`, so this can lead to weird behavior.  It also pre-supposes that the final label should be discarded.  Is this actually a convention?  Is there any utility to cutting off the last label for the user?  Depending on the answer to these questions, I'm in favor of removing the `label` argument from `util.boundaries_to_intervals`.

**Comment by bmcfee** [comment]
This is another artifact of trying to support salami annotations.

I'm okay with dropping it, since the behavior is generally ambiguous.

**Comment by craffel** [comment]
PR #152
