### ISSUE TITLE
Unit test for util.bipartite_match

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#153]
Currently, the `recurse` function in `util.bipartite_match` is not covered by tests.  This is probably because none of the test annotations have any annotations which are close enough to warrant recursion, or something.  We don't have a unit test for it in general.  @bmcfee, can you add one which covers this case?

**Comment by bmcfee** [comment]
I think you should be able to trigger this by doing an event match with very large window size. I'll try to work out a concrete example.

**Comment by craffel** [comment]
Resolved in 3a6a8ce53eb7974db52104a834210b505b43f711 and 5b8fdecc1703863208838a29d4207d7b75fb78ca
