### ISSUE TITLE
Docstring description for chord.tetrads is wrong?

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#159]
@ejhumphrey should this https://github.com/craffel/mir_eval/blob/master/mir_eval/chord.py#L933 read something like "Compare chords along tetrad (root, full quality, & bass) relationships." instead?

**Comment by ehumphrey85** [comment]
Yep, good catch!

**Comment by craffel** [comment]
Fixed in 5655a8dce3a498b355038aaff490b96c1e3e91a0
