### ISSUE TITLE
frame_size in mir_eval.util.intervals_to_samples docstring?

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#160]
@bmcfee I think you wrote the docstring for `intervals_to_samples`.  https://github.com/craffel/mir_eval/blob/master/mir_eval/util.py#L112
Is `frame_size` supposed to be `sample_size`?

**Comment by bmcfee** [comment]
Yup, good catch!

**Comment by craffel** [comment]
Fixed in 5655a8dce3a498b355038aaff490b96c1e3e91a0
