### ISSUE TITLE
Tests taking too long - travis timeouts

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#168]
Outstanding PRs are failing because travis is timing out on our tests after 30 minutes.

This might be a temporary issue with travis, though I'm not seeing it on my other repos.  More likely, something is taking way longer than it should in the test suite.  It's currently impossible to tell what the hold up is, since the tests don't run with verbose mode.

@craffel want to look into it?

**Comment by craffel** [comment]
> @craffel want to look into it?

Haha, no, not really, but I will.  I would guess it was the separation metrics, which take a very long time in slow/non-tuned settings.
