### ISSUE TITLE
sonify.chords, unique times strikes again

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#172]
There appears to be a bug in sonify.chords stemming from running unique on time events.  It's difficult to reproduce, since it boils down to numerical precision issues, but the resulting artifact is that some chords do not get sonified.

I've gisted a [notebook](https://gist.github.com/829701891958b7f9ae41) to illustrate the problem, but it depends on having the jams-sonify branch and beatles isophonics data, so it may take some effort to reproduce outside of my environment.  Still, I'm pretty sure this is caused by our old buddy [unique](https://github.com/craffel/mir_eval/blob/master/mir_eval/sonify.py#L213).

**Comment by craffel** [comment]
Yes, that looks wrong, and yes, unique would be my best guess...  Does rounding before calling unique fix this example for you?

**Comment by bmcfee** [comment]
Yup, sticking a `times = np.around(times, 3)` fixes it.

I'm curious as to why all this is necessary though; why not just take the first column of intervals as label start times?

**Comment by craffel** [comment]
By "all this" do you mean [this](https://github.com/craffel/mir_eval/blob/master/mir_eval/sonify.py#L211-L218)?  I believe it's because you coud have something like
```
Start | End  | Label
0.0   | 1.0  | C
1.5   | 2.0  | D
```
which you needed to convert to
```
Start | End  | Label
0.0   | 1.0  | C
1.0   | 1.5  | N
1.5   | 2.0  | D
```
Though I think we can avoid this now that you can pass intervals to `sonify.time_frequency`.

**Comment by bmcfee** [comment]
> Though I think we can avoid this now that you can pass intervals to sonify.time_frequency.

Yup. I'd forgotten that the implicit-end-time version existed. :)

I can open a PR that does this via intervals if that sounds good to you.

**Comment by craffel** [comment]
> I can open a PR that does this via intervals if that sounds good to you.

:+1:
