### ISSUE TITLE
hierarchy.evaluate(), forward-compatibility

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#177]
Dragging back up some discussion from #125...

The current `evaluate` function calls only one metric (tmeasures), which in turn only takes boundaries and not labels.  Consequently, `evaluate` only exposes positional arguments for boundaries.

I can imagine the not-too-distant future`*` in which we may have metrics for label hierarchies, which will require a change to the `evaluate` API.  The resulting api should look similar to `segment.evaluate()`, excepting that each of the inputs is a list of annotations (intervals or labels) instead of a single flat interval/label array.

The question here is: when should we change the API?

- Option 1: ASAP, to prevent too much breakage down the road
- Option 2: wait until a metric using the labels is introduced.

I'd advocate for the former, since it costs us nothing and will make the transition easier later on.  What do others think?

`*` I have an implementation of one such metric already, but it's nowhere near ready for PR/inclusion.

**Comment by craffel** [comment]
I'm fine with changing the API now.

**Comment by urinieto** [comment]
I vote option 1 too.
