### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#184]
There doesn't seem to be a changelog/release notes in the documentation.

We should definitely add this.

**Comment by bmcfee** [comment]
I looked into doing this, and it seems like we don't have milestone tags for most merged PRs.  This makes it really difficult to figure out which PRs merged for which releases.

@craffel could you create retroactive milestones (0.3, 0.2, 0.1) and we can then tag old PRs to make this easy?

**Comment by craffel** [comment]
> I looked into doing this, and it seems like we don't have milestone tags for most merged PRs. This e
makes it really difficult to figure out which PRs merged for which releases.
> @craffel could you create retroactive milestones (0.3, 0.2, 0.1) and we can then tag old PRs to make this easy?

There already are milestones for all of those releases: https://github.com/craffel/mir_eval/milestones?state=closed Apart from that, I don't think all contributions have been in PRs (except probably for 0.3) since lots of people have write access to the repo and we weren't doing PRs initially.  If you want to create a changelog retroactively, it probably makes more sense to just look at the list of commits (and the release notes) for each release: https://github.com/craffel/mir_eval/releases

**Comment by bmcfee** [comment]
> don't think all contributions have been in PRs (except probably for 0.3) since lots of people have write access to the repo and we weren't doing PRs initially.

Can we do it by issue instead?  I really don't want to rifle through the commit log.

**Comment by craffel** [comment]
> Can we do it by issue instead? I really don't want to rifle through the commit log.

Potentially, but then we might miss changes, as I don't think every change had an accompanying issue (or at least there may not be a 1-1 correspondence).  But you can already see issues assigned to each milestone:
https://github.com/craffel/mir_eval/milestone/6?closed=1
Or do you mean you want me to go back and assign each issue without a milestone to a milestone?

**Comment by bmcfee** [comment]
> Or do you mean you want me to go back and assign each issue without a milestone to a milestone?

Yes.

**Comment by craffel** [comment]
Ok, I will try to make a 1-1 correspondence before the next release.

**Comment by bmcfee** [comment]
That might be overkill, but as long as we catch the important issues, that's fine.

I don't mind doing the sphinxification.

**Comment by bmcfee** [comment]
I started the PR: i don't think we need a changelog for anything before 0.1.

In terms of issue assignment:

- 0.2 looks pretty complete
- 0.3 is totally missing
- 0.4 looks good so far.

If you can just track down the issues resolved between 0.2 and 0.3 (by date?) that would be helpful.

**Comment by stefan-balke** [comment]
When is the release planned? Could make use of some of the viz functions but jams PR is on halt until 0.4 is ready.

**Comment by craffel** [comment]
No definite release date planned, but it will basically be ready once all the new source separation stuff is merged and the 0.4 issues are resolved.  We may punt on #197.  So, soon.

**Comment by faroit** [comment]
> No definite release date planned, but it will basically be ready once all the new source separation stuff is merged and the 0.4 issues are resolved.

Sounds great. [dsdtools](https://github.com/faroit/dsdtools/tree/WIP_eval) is already prepared to support 0.4 ;-)

**Comment by bmcfee** [comment]
closed by merging #211
