### ISSUE TITLE
Load delimited skips the first line?

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#187]
Here: https://github.com/craffel/mir_eval/blob/master/mir_eval/io.py#L73

Does anyone know why it does this? I assume it is because some annotation files have a header, but I would not assume all annotation files do; this should be a function argument, I think.  Looks like it showed up [here](https://github.com/craffel/mir_eval/commit/08db16f586ec7d813e53fe38451e2557de94931c), maybe.  @bmcfee can you confirm?

@rabitt noticed this [here](https://github.com/craffel/mir_eval/pull/186#discussion-diff-56299780)

**Comment by bmcfee** [comment]
It doesn't skip the first line.  It starts the enumeration at 1 instead of 0.  This is so that errors reported below correctly report the offending line number in the input file.

**Comment by craffel** [comment]
Derp, thanks.
