### ISSUE TITLE
Code review integration?

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#206]
@craffel any thoughts about adding a code review integration tool?  Some of the CR here is getting difficult to keep track of across revisions, and something like [reviewable](https://github.com/integrations/reviewable), [review ninja](https://github.com/integrations/reviewninja), or [pull approve](https://github.com/integrations/pullapprove) could help.

(FWIW, I've been using reviewable and it's mostly pretty good.)

**Comment by craffel** [comment]
I'm not opposed to it, but I've never used any of them, so I don't really know what we're missing.  I don't have the bandwidth to learn/integrate now, but am open to it soon.

**Comment by craffel** [comment]
It sounds great.  I assume it will be messy to do while we are in the midst of CR/PRs though, so maybe we can do this once the outstanding PRs are merged?

**Comment by bmcfee** [comment]
Nah, it's all pretty non-invasive; everything shows up on github as comments.  It's more a matter of adopting procedure than anything else.  But it's your call, check it out whenever.

If you want to see the process, check out [this open PR](https://github.com/librosa/librosa/pull/323) on librosa.

**Comment by bmcfee** [comment]
While at this, how about adding a https://dependencyci.com/ integration?

**Comment by stefan-balke** [comment]
+1 here for CR tool.

**Comment by bmcfee** [comment]
@craffel now that 0.4 is out, any objection to me adding this?

**Comment by craffel** [comment]
Sure, go for it.

**Comment by bmcfee** [comment]
derp, it looks like only the repo owner can do it. :cry:

**Comment by craffel** [comment]
Ok, I can do it.  Which one did you end up choosing?

**Comment by bmcfee** [comment]
I like reviewable.

**Comment by craffel** [comment]
How about using [GitHub's new built-in code review features](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features)?

**Comment by bmcfee** [comment]
Oh snap.

**Comment by bmcfee** [comment]
> How about using GitHub's new built-in code review features?

After poking around github's new CR stuff, I'm not sure it's the best way to go.  I think I prefer reviewable's status management and comment thread system, but I'll leave the call to @craffel.

**Comment by craffel** [comment]
Having never used either, I'd rather start with the simple, built-in solution than try something external, especially if the external one has more features.  If we are finding GitHub's approach is awkward/not enough, we can consider switching.
