### ISSUE TITLE
Make validate_chord_label more strict

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#217]
I think it would be usful if `validate_chord_label` would raise an exception for any invalid chord, rather than the specific things it looks for.  For example, `mir_eval.chord.validate_chord_label('asdf')` passes without an exception.  Can we formalize what exactly a valid chord label is, and put it in this function?  @ejhumphrey do you have bandwidth for this?

**Comment by bmcfee** [comment]
Feel free to use the [jams chord regexp](https://github.com/marl/jams/blob/master/jams/schemata/namespaces/chord/chord.re) for this.

**Comment by bmcfee** [comment]
... it might also make sense, if anyone's so inclined, to use the regexp to redo `chord.split` using back-references.  There's nothing wrong with the current implementation (AFAIK), but if we already have the regexp, it would be much simpler to use it for parsing chord strings, and would eliminate a good amount of code.
