### ISSUE TITLE
Question interval util function

### ISSUE THREAD

**Issue by georgid** [craffel/mir_eval#228]
Hi, is there a function opposite to what `mir_eval.util.intervals_to_samples` does?
i.o.w.  I give it a list of equally-spaced sample points and it creates intervals
for input 
ts   label
0.1 A
0.2 A
0.3 A
0.4 B
0.5 B
0.6 A
0.7 A
it would return 
0.1 0.4 A
0.4 0.6 B
0.6 0.7 A
Thanks!

**Comment by craffel** [comment]
No, sorry, there isn't.
