### ISSUE TITLE
Web service not available

### ISSUE THREAD

**Issue by stefan-balke** [craffel/mir_eval#230]
Hi,

since the webservice is not available we should either delete it from the README.md or setup some other resources for that.

Opinions?

**Comment by craffel** [comment]
> we should either delete it from the README.md or setup some other resources for that.

Or we could, you know, fix the webservice!  This was caused by the labrosa webserver crashing and losing the appropriate apache configuration to successfully deploy the proxy to http://mireval.herokuapp.com/ (where the service actually lives).  Now fixed.
