### ISSUE TITLE
matplotlib 2.0 may break regression tests on display module

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#233]
Just putting this issue here, since the new release might change some of the default settings in ways that cause the regression tests to fail.

My advice is to update the build requirements for testing to `matplotlib >= 2.0.0` and re-generate the test cases accordingly.  People can still run code on 1.5, but testing should stay up to date.

**Comment by craffel** [comment]
Ok, thanks.

> re-generate the test cases accordingly

How did you generate the test cases in the first place?

**Comment by bmcfee** [comment]
Ran the tests functions, checked the output manually, and then copied over to baseline images.

I can take care of this in a few days.

**Comment by craffel** [comment]
Ok, cool.
