### ISSUE TITLE
use proper ticker locators for display.labeled_intervals

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#244]
This is a minor peeve that I'll probably fix this afternoon:

In interactive mode, the `labeled_intervals` plots do not show the correct vertical axis information in the mouse coordinate display (lower-right of the display window).  This is because tick labels are set directly to the axis, and not run through a `Locator` object from matplotlib.

It should be trivial to swap the tick labeling code out for a `FixedLocator` object to fix this.  `librosa.display` does this for tonnetz plots, so we have a model to work from.

This change should have no perceivable difference in static plots.

**Comment by craffel** [comment]
Cool, thank you.
