### ISSUE TITLE
sonify.chord, X should be silent but sounds like garbage

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#246]
Title says it all.

Background: the chord module distinguishes two "non-chord" labels:

- `N` (no-chord) used to indicate things like silence, crowd noise, or sounds that have no harmony
- `X` (unknown) used to indicate, as far as I can tell, out-of-gamut chords.

The `X` label mainly comes up when a predictor can only operate in a reduced label space (eg, is not allowed to predict 9ths), but you still want to model those observations as distinct from `N`.

When these are encoded via [`chord.encode`](https://github.com/craffel/mir_eval/blob/master/mir_eval/chord.py#L99-L102), the `N` label maps to an empty set of pitch classes.  The `X` label maps to a vector of all `-1`, which gets sonified as button-mashing the keyboard.

Proposed change: `sonify.time_frequency` thresholds `gram` at 0 so that negative amplitudes are treated as silence.  This would solve the problem indirectly, and prevent similar mishaps from popping up elsewhere.

**Comment by craffel** [comment]
Good catch.

> Proposed change: sonify.time_frequency thresholds gram at 0 so that negative amplitudes are treated as silence. This would solve the problem indirectly, and prevent similar mishaps from popping up elsewhere.

Seems reasonable to me, provided there's a note in the docstring to this effect.
