### ISSUE TITLE
Travis fails with cannot import name 'KnownFailureTest'

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#267]
https://travis-ci.org/rabitt/mir_eval/jobs/298700718#L2022

Looks like KnowFailureTest doesn't exist in Matplotlib anymore (maybe because of a new release), which is used by `mpl_ic.py` [here](https://github.com/craffel/mir_eval/blob/master/tests/mpl_ic.py#L26).  @bmcfee if you have a quick fix a PR is welcome otherwise I will investigate later.

**Comment by bmcfee** [comment]
Ill try to get back to this matter in the week.

**Comment by bmcfee** [comment]
Yup, mpl 2.1 moved from nose to pytest, which is something we should also do.  I'll see about hacking `mpl_ic.py` back into working shape for the time being.
