### ISSUE TITLE
Separation Evaluation Error: All sources should be non-silent

### ISSUE THREAD

**Issue by MR-T77** [craffel/mir_eval#280]
Hi!
I'm trying to evaluate signal separation algorithms, but I'm unable to do it as in `mir_eval.separation.validate(reference, estimated)` I always get the error 

> ValueError: All the reference sources should be non-silent (not all-zeros), but at least one of the reference sources is all 0s, which introduces ambiguity to the evaluation...

My reference is `voc_array` (here I send some stats about this numpy array -dtype= float32):
```
np.mean(voc_array)
Out[17]: 8.973399e-06
np.max(voc_array)
Out[18]: 0.2822876
np.std(voc_array)
Out[19]: 0.059242096
np.shape(voc_array)
Out[20]: (2094534, 1)
```

Can you help me?
Thanks in advance

**Comment by craffel** [comment]
Your `voc_array` is transposed. It should be of shape `(n_sources, n_samples)`, so `(2094534, 1)`.  The docstrings all state this.

**Comment by bmcfee** [comment]
The docstrings do explain this, but this seems like the wrong exception to throw.  Or, at least, the message being given is not as helpful as it could be.

**Comment by faroit** [comment]
> The docstrings do explain this, but this seems like the wrong exception to throw. Or, at least, the message being given is not as helpful as it could be.

indeed, maybe it would make sense to move up the [number of sources check](https://github.com/craffel/mir_eval/blob/master/mir_eval/separation.py#L111) in the validation function so that is triggered before the silence validation.

**Comment by MR-T77** [comment]
Thanks. Sorry for not getting it from the documentation, but I was focusing on the error message.
