### ISSUE TITLE
why is SDR not infinity even though reference and estimate are eqaul?

### ISSUE THREAD

**Issue by chosw93** [craffel/mir_eval#285]
I put the same audio file in both inputs of the  'bss_eval_sources' function.
but SDR is not infinity but around 290 dB...
Why does this happen?

**Comment by faroit** [comment]
This is probably due to some numerical instabilities. Are you running it on 32bit floats? Have you tried [BSSeval v4](https://sigsep.github.io/sigsep-mus-eval/museval.metrics.html) for comparison.

**Comment by bmcfee** [comment]
Can you provide a full example code snippet that reproduces this behavior?  (Synthetic signals ought to be fine for this.)

My hunch is that it's just a numerical precision / stability quirk.  290 dB may as well be infinite, but the check for returning `np.Inf` requires an exact 0: https://github.com/craffel/mir_eval/blob/master/mir_eval/separation.py#L827-L834 .

**Comment by chosw93** [comment]
@faroit 
Thank you for answer me! 
The variable type is 32bit float. And the BSSeval v4 ('.metrics.bss_eval_source's) also return around 290 dB. 
i just accept that 290dB is infinity.

**Comment by faroit** [comment]
did you try with dtype 64bit float?

**Comment by chosw93** [comment]
@faroit @bmcfee 
Float64 is also same  as float32.

In the debug mode in pycharm, i will check that e_spat is not zero. 
So, in '_safe_db' function, denominator also not zero but very small value.

why is the 'e_spat' non-zero?
