### ISSUE TITLE
strict validate_chord_label in 0.4 release

### ISSUE THREAD

**Issue by hvkoops** [craffel/mir_eval#287]
Although issue #217 was solved by bmcfee in #242 , it is still present in the current 0.4 release, which results in undesired behavior.
For example
`mir_eval.chord.validate_chord_label('C:maj')` 
and 
`mir_eval.chord.validate_chord_label('iwufhiweuhf')`
both pass without an exception.

**Comment by craffel** [comment]
#242 was merged after 0.4 was released. If you want to use the code committed in #242, you'll need to run from master, not from 0.4. There's no plans to make a release in the immediate future, but on the other hand we could do one now if there's demand.

**Comment by bmcfee** [comment]
We do seem to have a lot of merged PRs since the last release in 2016. I'd be in favor of a 0.5 release just to get those things out there.

**Comment by craffel** [comment]
Cool, I can make one in the not-too-distant-future.

**Comment by hvkoops** [comment]
A 0.5 release would be great! Thanks for the awesome work. If there is anything I can do, please let me know.

**Comment by craffel** [comment]
Ok, [0.5 release created](https://github.com/craffel/mir_eval/releases/tag/0.5) and [on PyPI](https://pypi.org/project/mir_eval/0.5/), and [docs are updated](https://craffel.github.io/mir_eval/)! Closing this issue.
