### ISSUE TITLE
Deprecation warning in hierarchy

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#303]
The tests for hierarchy generate so many of the following warning that Travis quits:
https://travis-ci.org/craffel/mir_eval/jobs/477467833#L1241
Apparently somewhere in scipy's sparse matrix implementation, they use the numpy matrix class, and numpy now warns whenever the matrix class is used. See e.g. https://github.com/scipy/scipy/issues/9093
https://github.com/scikit-learn/scikit-learn/issues/12327
@bmcfee do you know where in the hierarchy code this would be triggered?

**Comment by bmcfee** [comment]
not off the bat -- I can take a look at this later in the week.

In general, mir_eval is due for an audit of upstream deprecation warnings, so it might be better to handle that all in one go.  I just did the same for librosa, and it was a bit of a pain, but not too bad.

Worst case, you can set certain warnings / modules to only display once during testing, which should "fix" this in the short term.

**Comment by craffel** [comment]
Fixed in #305
