### ISSUE TITLE
Couldn't convert value

### ISSUE THREAD

**Issue by Irinnisar** [craffel/mir_eval#315]
When I've tried to use mir_eval onset or beat evaluation code, I got this error.

`ValueError: Couldn't convert value  using float found at models/wa4/ah_development_guitar_Guitar_Licks_07-06.onsets:3:
`
What should I do to solve the problem?

**Comment by craffel** [comment]
It looks like you are trying to load in the file 
`models/wa4/ah_development_guitar_Guitar_Licks_07-06.onsets`
using `mir_eval.io.load_events` (or some other `io` function), but the third line of that file has a value that cannot be converted to a float using the `float()` built-in function. You need to fix your file.
