### ISSUE TITLE
structural segmentation

### ISSUE THREAD

**Issue by surajsonee** [craffel/mir_eval#321]
Do i get the structural segmentation of music like intro, chorus, verse, bridge and outro?

Thanks!

**Comment by craffel** [comment]
This package evaluates structural segmentation algorithms, it does not compute a structural segmentation of a given song. For that you might want to try MSAF
https://github.com/urinieto/msaf

**Comment by urinieto** [comment]
MSAF provides structural segmentation, but the segment labels that it yields are not _functional_ (i.e., they're not semantically meaningful like chorus, verse, etc)

**Comment by surajsonee** [comment]
okay no problem!  but which section of code i can try in MSAF to get the structual segmenation. now labelling is not important for me.
Thanks

**Comment by urinieto** [comment]
This notebook should be pretty self explanatory: https://github.com/urinieto/msaf/blob/master/examples/Run%20MSAF.ipynb
