### ISSUE TITLE
`separation.bss_eval_sources()` and `separation.bss_eval_sources_framewise()`

### ISSUE THREAD

**Issue by Yossarian0916** [craffel/mir_eval#325]
Although the docs describe the differences between these two functions, it's still unclear, even the returned results from these two functions have different shapes. Could someone elaborate the differences and the usage of `separation.bss_eval_sources()` and `separation.bss_eval_sources_framewise()`?

**Comment by craffel** [comment]
@faroit Any thoughts?

**Comment by faroit** [comment]
`bss_eval_sources_framewise` computes several `bss_eval_sources` as set by the `window` and `hop` parameter. if your signals are short: use non-framewise, if your signals are long >10s, use the framewise metric.

https://github.com/craffel/mir_eval/blob/19ed4dfbc193f9de48e56fc34198556fd3de3766/mir_eval/separation.py#L591-L601
