### ISSUE TITLE
Docs website missing styling (css/js)

### ISSUE THREAD

**Issue by ethman** [craffel/mir_eval#329]
Looks like almost all of the js and css references are 404'ing on the published version of the website (https://craffel.github.io/mir_eval/). Tested on Firefox, Safari, and Chrome on OS X.

**Comment by craffel** [comment]
Thanks, this was broken in the recent docs update and just fixed it in https://github.com/craffel/mir_eval/commit/01920c9105a46d2121f4918b719fcdd239ea4d79

**Comment by ethman** [comment]
Yup, looks good! Thanks!
