### ISSUE TITLE
sonify.pitch_contour should support nans

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#332]
Minor inconvenience, but for f0 estimation, it's nice to be able to use `nan` to encode missing/unvoiced regions (rather than 0, or egad, negative frequency).  Doing so breaks the sonifier, but it would be an easy enough fix to support it.

**Comment by craffel** [comment]
Is there a convention to use `nan` to mean "missing/unvoiced"?

**Comment by bmcfee** [comment]
Not specifically, but it's common to use `nan` for missing data in general, and I think this qualifies.  (FWIW, librosa.pyin uses nan for unvoiced frames by default.)

**Comment by craffel** [comment]
"PRs welcome", as they say
