### ISSUE TITLE
Evaluation of SDR and SIR

### ISSUE THREAD

**Issue by ShinichiTakayama-JP** [craffel/mir_eval#347]
Hello.
I would like to evaluate SDR and SIR.
I am running the following sample code.
```
import mir_eval

reference_beats = mir_eval.io.load_events('reference_beats.txt')
estimated_beats = mir_eval.io.load_events('estimated_beats.txt')

scores = mir_eval.beat.evaluate(reference_beats, estimated_beats)

print(scores)
```

I have some questions.
What do I put in `reference_beats.txt` and `estimated_beats.txt`?
Is it the path to the wav file?
When I put the path to the wav file in the text file, I get the following error.

> (eval_test) C:\Users\4020737\Documents\git\MirEval\mir_eval>python test.py
Traceback (most recent call last):
  File "C:\Users\4020737\Documents\git\MirEval\mir_eval\mir_eval\io.py", line 108, in load_delimited
    converted_value = converter(value)
ValueError: could not convert string to float: 'C:\\Users\\4020737\\Documents\\git\\MirEval\\mir_eval\\data\\ref.wav'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    reference_beats = mir_eval.io.load_events('reference_beats.txt')
  File "C:\Users\4020737\Documents\git\MirEval\mir_eval\mir_eval\io.py", line 149, in load_events
    events = load_delimited(filename, [float],
  File "C:\Users\4020737\Documents\git\MirEval\mir_eval\mir_eval\io.py", line 110, in load_delimited
    raise ValueError("Couldn't convert value {} using {} "
ValueError: Couldn't convert value C:\Users\4020737\Documents\git\MirEval\mir_eval\data\ref.wav using float found at ref
erence_beats.txt:1:
        C:\Users\4020737\Documents\git\MirEval\mir_eval\data\ref.wav

Could you please tell me the procedure for evaluating SDR and SIR?

Best regards.

**Comment by ShinichiTakayama-JP** [comment]
My environment is as follows.
I installed using `>python setup.py install`
> ca-certificates           2022.4.26            haa95532_0
certifi                   2022.6.15        py38haa95532_0
future                    0.18.2                   pypi_0    pypi
numpy                     1.23.0                   pypi_0    pypi
openssl                   1.1.1o               h2bbff1b_0
pip                       21.2.2           py38haa95532_0
python                    3.8.13               h6244533_0
scipy                     1.8.1                    pypi_0    pypi
setuptools                61.2.0           py38haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.3               h2bbff1b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py38haa95532_2

**Comment by craffel** [comment]
Your example code seems to be for beat evaluation, not SDR/SIR evaluation. You can use https://craffel.github.io/mir_eval/#mir_eval.separation.bss_eval_sources
