### ISSUE TITLE
Migrate pull request automated testing from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by carlthome** [craffel/mir_eval#354]
To help make sure mir_eval stays in good shape as its dependencies moves, it would be convenient to have test automation for PRs to make reviews easier. Time flies, Travis CI seems broken (?), and the world has moved to GitHub Actions.

I'm wondering if you'd like to have automated testing by a .github/workflows/ci.yaml - if so, I could draft a proposal in a PR (since I happen to have professional work hours to spend on helping out currently).

👍 / 👎 ❓

**Comment by bmcfee** [comment]
This would be great, and long overdue.

In setting this up, I would also advocate for breaking up some of the CI functionality across different workflows, so that there are separate actions for unit tests, linting, and doc testing.
