### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by justinsalamon** [craffel/mir_eval#74]
Apparently in python 3 the print statement was replaced with a print function, meaning that instead of 
```print x``` you need to call ```print(x)```. Consequently, this breaks mir_eval on Python 3 (brought to my attention by someone trying to use mir_eval on Windows 7 with Python 3.4). 

Perhaps we should replace all calls to ```print x``` with e.g. ```sys.stdout.write(x)``` which should work both on python 2 and 3?

**Comment by craffel** [comment]
This should be handled by #113.
