### ISSUE TITLE
tempo estimation validation

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#99]
I just finished validating mir_eval's tempo estimation metrics against (private) MIREX 2014 data.  Everything validates to machine precision.

I think we're safe merging the develop branch back into master.

TO-DO:

- [x] add regression tests for tempo evaluation

**Comment by bmcfee** [comment]
This one should be closed as well via #131, right?

**Comment by craffel** [comment]
Check that damn box first!

**Comment by bmcfee** [comment]
:white_check_mark:
